### ISSUE TITLE
Reference(s) Roadmap?

### ISSUE THREAD

**Issue by laurentsenta** [pln-planning-tools/MapLight#381]
Does the tool have a Roadmap itself? I was expecting to find a link at the top of the doc with one or more Roadmap I could use as examples.

Having a working example would help me write my own Roadmap and identify my mistakes,

For example, the [doc](https://github.com/pln-planning-tools/Starmap/blob/main/User%20Guide.md#using-github-tasklists) gives this snippet:

```
```[tasklist]
### Any descriptor or other text
- [ ] #123 <!-- will be recognized by starmap -->
- [ ] org/repo#123 <!-- will be recognized by starmap -->
- [ ] some non-link description <!-- will NOT be recognized by starmap -->
- [ ] https://github.com/org/repo/issue/987 <!-- will be recognized by starmap -->

### Any text
- [ ] #456 <!-- will be recognized by starmap -->
- [ ] org/repo#567 <!-- will be recognized by starmap -->
- [ ] https://github.com/other-org/other-repo/issue/987 <!-- will be recognized by starmap -->

\```
```

I get a rendering error when I use this format in my project.

```
```[tasklist]
### Gateway Conformance
- [ ] https://github.com/ipfs/gateway-conformance/issues/120
- [ ] https://github.com/ipfs/gateway-conformance/issues/119
### Test Coverage
- [ ] https://github.com/ipfs/gateway-conformance/issues/121
\```
```

It seems like we have to use two task lists:

```
```[tasklist]
### Gateway Conformance
- [ ] https://github.com/ipfs/gateway-conformance/issues/120
- [ ] https://github.com/ipfs/gateway-conformance/issues/119
\```

```[tasklist]
### Test Coverage
- [ ] https://github.com/ipfs/gateway-conformance/issues/121
\```
```

But then the second gets ignored (https://starmap.site/roadmap/github.com/ipfs/gateway-conformance/issues/122#view=list)

**Comment by SgtPooki** [comment]
@laurentsenta Good catch that multiple tasklists are not currently supported. 

As for Starmap having its own roadmap, the team maintaining the tool is split between many projects currently and we've got little time for running project management here.

Part of the problem of using a github issue as an example roadmap, is it's only beneficial for users who can `edit` that issue to see the source markdown. 

### Next actions:

- [ ] ensure multiple tasklists can be read from a github issue description
- [ ] update examples to ensure the markdown is accurate and can be rendered properly.
